spring:
  application:
    name: catalog-service-parcial
  config:
    import: configserver:http://localhost:8888

resilience4j.circuitbreaker:
  instances:
    movies:
      failure-rate-threshold: 50
      wait-duration-in-open-state: 5s
      permitted-number-of-calls-in-half-open-state: 2
      sliding-window-type: COUNT_BASED
      sliding-window-size: 2
resilience4j.retry:
  retryAspectOrder: 2
  instances:
    movies:
      maxAttempts: 2
      waitDuration: 10
      retryExceptions:
        - feign.FeignException$InternalServerError

management:
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always

