spring:
  application:
    name: catalog-service-parcial
  config:
    import: configserver:http://localhost:8888

# configuracion de circuitbraker: cuando falla 2 veces, activa el plan de contingencia, y espera solo 10 segundos para reactivarse
#resilience4j.circuitbreaker:
#  circuitBreakerAspectOrder: 1
#  instances:
#    movies:
#      allow-health-indicator-to-fail: false
#      register-health-indicator: true
#      sliding-window-type: COUNT_BASED
#      sliding-window-size: 2
#      failure-rate-threshold: 50
#      wait-duration-in-open-state: 10s
#      permitted-number-of-calls-in-half-open-state: 2
#      automatic-transition-from-open-to-half-open-enabled: true
#resilience4j.retry:
#  retryAspectOrder: 2
#  instances:
#    movies:
#      max-attempts: 2
#      wait-duration: 10
#      retry-exceptions:
#        - [ 0 ]: feign.FeignException$InternalServerError
resilience4j.circuitbreaker:
  instances:
    movies:
      failure-rate-threshold: 50
      wait-duration-in-open-state: 5s
      permitted-number-of-calls-in-half-open-state: 2
      sliding-window-type: COUNT_BASED
      sliding-window-size: 2
management:
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
