spring:
  application:
    name: serie-service-parcial
  config:
    import: configserver:http://localhost:8888

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  serie:
    name: NewSerie